name: mock_chat_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  animations: ^2.0.7
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  firebase_database: ^10.1.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.4
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  riverpod: ^2.3.4

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  mockito: ^5.4.0

flutter:
  uses-material-design: true
